//
// Created by MCXCC on 2024/8/8.
//

#ifndef LAGRANGE_INTERPOLATION_FRACTIONSIMPLIFIER_H
#define LAGRANGE_INTERPOLATION_FRACTIONSIMPLIFIER_H

long long *Simplifier(long long *arr);

#endif //LAGRANGE_INTERPOLATION_FRACTIONSIMPLIFIER_H
